#!/usr/bin/env node

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { validateManifest } from './manifest-validator.mjs';
import { readLegacyContentEntries } from './source-reader.mjs';

const GENERATED_HEADER = '// Generated by scripts/content/build-catalog.mjs. Do not edit.';

const compareText = (left, right) => (left < right ? -1 : left > right ? 1 : 0);
const compareById = (left, right) => compareText(left.id, right.id);

const collectManifestFiles = async (rootDir, expectedName) => {
  const files = [];

  const walk = async (dirPath) => {
    let entries;
    try {
      entries = await readdir(dirPath, { withFileTypes: true });
    } catch (error) {
      if (error?.code === 'ENOENT') return;
      throw error;
    }

    for (const entry of entries.sort((left, right) => compareText(left.name, right.name))) {
      const entryPath = path.join(dirPath, entry.name);
      if (entry.isDirectory()) {
        await walk(entryPath);
      } else if (entry.isFile() && entry.name === expectedName) {
        files.push(entryPath);
      }
    }
  };

  await walk(rootDir);
  return files;
};

const readManifests = async (repoRoot) => {
  const files = [
    ...await collectManifestFiles(path.join(repoRoot, 'games'), 'game.manifest.json'),
    ...await collectManifestFiles(path.join(repoRoot, 'classrooms'), 'classroom.manifest.json'),
  ].sort(compareText);

  const manifests = [];
  for (const filePath of files) {
    const source = path.relative(repoRoot, filePath).replace(/\\/g, '/');
    let parsed;
    try {
      parsed = JSON.parse(await readFile(filePath, 'utf8'));
    } catch (error) {
      throw new Error(`${source}: invalid JSON (${error.message})`, { cause: error });
    }
    manifests.push(validateManifest(parsed, source));
  }
  return manifests;
};

const assertUniqueIds = (values, label) => {
  const ids = new Set();
  for (const value of values) {
    if (ids.has(value.id)) throw new Error(`Duplicate ${label} id: ${value.id}`);
    ids.add(value.id);
  }
};

const buildLegacyPathMap = (contentItems, experiences) => {
  const pathIds = new Map();
  const addContentPath = (legacyPath, id) => {
    const ids = pathIds.get(legacyPath) ?? new Set();
    ids.add(id);
    pathIds.set(legacyPath, ids);
  };

  for (const item of contentItems) {
    if (item.customHtmlPath) addContentPath(item.customHtmlPath, item.id);
  }
  for (const experience of experiences) {
    for (const legacyPath of experience.compatibility.legacyPaths) {
      const ids = pathIds.get(legacyPath);
      if (ids && !ids.has(experience.id)) {
        throw new Error(`Duplicate legacy path: ${legacyPath} (${[...ids].join(', ')}, ${experience.id})`);
      }
      addContentPath(legacyPath, experience.id);
    }
  }

  return Object.fromEntries(
    [...pathIds.entries()]
      .sort(([left], [right]) => compareText(left, right))
      .map(([legacyPath, ids]) => [legacyPath, [...ids].sort()[0]]),
  );
};

const serializeCatalog = ({ contentItems, experiences, legacyPaths }) => [
  GENERATED_HEADER,
  '',
  "import type { ExperienceManifest } from '@homeschool/content-schema';",
  "import type { ContentItem } from '../types/content';",
  '',
  `export const GENERATED_CONTENT_ITEMS: ContentItem[] = ${JSON.stringify(contentItems, null, 2)};`,
  '',
  `export const GENERATED_EXPERIENCES: ExperienceManifest[] = ${JSON.stringify(experiences, null, 2)};`,
  '',
  `export const GENERATED_LEGACY_PATHS: Readonly<Record<string, string>> = ${JSON.stringify(legacyPaths, null, 2)};`,
  '',
].join('\n');

const createCatalog = async (repoRoot) => {
  const contentItems = readLegacyContentEntries({ repoRoot }).sort(compareById);
  const experiences = (await readManifests(repoRoot)).sort(compareById);
  assertUniqueIds(contentItems, 'legacy content');
  assertUniqueIds(experiences, 'manifest');

  const legacyPaths = buildLegacyPathMap(contentItems, experiences);
  const output = serializeCatalog({ contentItems, experiences, legacyPaths });

  return { contentItems, experiences, legacyPaths, output };
};

export const buildCatalog = async ({ repoRoot, outputFile }) => {
  const result = await createCatalog(repoRoot);
  await mkdir(path.dirname(outputFile), { recursive: true });

  let current = null;
  try {
    current = await readFile(outputFile, 'utf8');
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }
  if (current !== result.output) await writeFile(outputFile, result.output, 'utf8');

  return result;
};

const main = async () => {
  const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
  const outputFile = path.join(repoRoot, 'src', 'generated', 'contentCatalog.ts');
  const checkOnly = process.argv.includes('--check');

  if (checkOnly) {
    let expected;
    try {
      expected = await readFile(outputFile, 'utf8');
    } catch (error) {
      if (error?.code === 'ENOENT') {
        throw new Error('Generated catalog is missing. Run npm run sync:content-catalog.');
      }
      throw error;
    }

    const result = await createCatalog(repoRoot);
    if (result.output !== expected) {
      throw new Error('Generated catalog is stale. Run npm run sync:content-catalog.');
    }
    console.log(`Catalog is current: ${result.contentItems.length} content entries, ${result.experiences.length} manifests.`);
    return;
  }

  const result = await buildCatalog({ repoRoot, outputFile });
  console.log(`Generated ${result.contentItems.length} content entries and ${result.experiences.length} manifests.`);
};

const isMain = process.argv[1]
  && path.resolve(process.argv[1]).toLowerCase() === fileURLToPath(import.meta.url).toLowerCase();

if (isMain) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
